### PR TITLE
[#1] Created killing of angels and bullets crash

### LINKED ISSUE #1: Create killing of Angels (Collision)

### PR DESCRIPTION
**Pull request by nriker**

### CODE REVIEW

File: src/game/collision.ts [hunk 1]
```diff
@@ -1,12 +1,22 @@
...
 export function isCollision(circle: Circle, rectangle: Rectangle): boolean {
-  //TODO
+  let circleRadiusX = circle.x + circle.radius;
+  let circleRadiusY = circle.y + circle.radius;
+  return rectangle.x <= circleRadiusX && rectangle.y <= circleRadiusY
+      && (circle.x - rectangle.x) <= circle.radius
+      && Math.abs(rectangle.y - circleRadiusY) <= rectangle.height;
+}
+
+function killAngel(angel: TypedSprite, gameState: GameState) {
```
Comment (LuccaHellriegel) [inline src/game/collision.ts]: I would propose a general "removeSprite" function that is then used here. Both functions are functionally the same at the moment.

**Review by LuccaHellriegel — CHANGES_REQUESTED** [review]
one minor nitpick, rest looks good

File: src/game/collision.ts (hunk 1 above)
Comment (nriker) [reply src/game/collision.ts]: I agree, fixed

**Review by LuccaHellriegel — APPROVED** [review]
